---
- hosts: all
  gather_facts: false
  become: true

  tasks:
  - name: install python
    raw: "DEBIAN_INTERACTIVE=false apt-get -y install python bzip2 software-properties-common"

  - name: add ppas
    apt_repository:
      repo: "{{ item }}"
    with_items:
      - "ppa:certbot/certbot"
      - "ppa:teward/znc"

  - name: install certificates
    unarchive:
      src: le.tar.bz2
      dest: /
      keep_newer: yes

  - name: znc user
    user:
      name: znc
      system: yes

  - name: znc tarball
    unarchive:
      src: znc.tar.bz2
      dest: /
      owner: znc
      group: znc
      keep_newer: yes

  - name: install packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
        - certbot
        - openssl
        - znc

  - name: allow znc to bind below 1024
    command: "setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/znc"

  - name: generate dhparam.pem
    command: "openssl dhparam -out /root/dhparam.pem 2048"
    args:
      creates: /root/dhparam.pem

  - name: renewal script
    copy:
      src: renew_cert.sh
      dest: /root/
      mode: "0755"

  - name: cron job for cert renewal
    cron:
      name: cert renewals
      special_time: weekly
      job: "/root/renew_cert.sh"

  - name: install systemd unit
    copy:
      src: znc.service
      dest: /lib/systemd/system

  - name: install and start znc module
    systemd:
      name: znc
      enabled: yes
      state: started
